[package]
name = "hlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
pest = "2.7.7"
pest_derive = "2.7.7"
chrono = "0.4.34"